name: Windows Portable AppImage

on:
  push:
    paths:
      - '.github/workflows/win-appimage.yml'
      - 'pom.xml'
      - 'src/**'
      - 'packaging/windows/**'
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 22 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Build (skip tests)
        run: mvn -q -DskipTests package

      - name: Compute JAR name
        shell: pwsh
        run: |
          $jar = Get-ChildItem -Path target -Filter 'embassyfx-*.jar' |
            Where-Object { $_.Name -notmatch 'sources|javadoc' } |
            Select-Object -First 1
          if (-not $jar) { throw "No embassyfx-*.jar found in target/"; }
          "JAR_NAME=$($jar.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Using JAR: $($jar.Name)"

      - name: Stage runtime deps (JAR + dependencies)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path target/deps | Out-Null
          Copy-Item "target/${{ env.JAR_NAME }}" target/deps/
          mvn -q dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/deps

      - name: Fetch JavaFX (Windows) jars
        shell: pwsh
        run: |
          $JfxVer = '22.0.2'
          $mods = @('base','graphics','controls','fxml')
          foreach ($m in $mods) {
            mvn -q dependency:get -Dartifact="org.openjfx:javafx-$m:$JfxVer:win"
            $jar = Join-Path $env:USERPROFILE ".m2\repository\org\openjfx\javafx-$m\$JfxVer\javafx-$m-$JfxVer-win.jar"
            if (-not (Test-Path $jar)) { throw "Missing JavaFX jar: $jar" }
            Copy-Item $jar target/deps/
          }

      - name: jpackage (Windows app-image)
        shell: pwsh
        run: >
          jpackage
          --type app-image
          --name EmbassyFX
          --dest packaging\windows
          --input target\deps
          --main-jar ${{ env.JAR_NAME }}
          --main-class app.Main
          --app-version 1.0.0
          --icon packaging/windows/AppIcon.ico
          --java-options '--module-path %APPDIR%\app --add-modules=javafx.controls,javafx.fxml,javafx.graphics,javafx.base'

      - name: Zip portable folder
        shell: pwsh
        run: |
          $src = 'packaging/windows/EmbassyFX/*'
          $dst = 'packaging/windows/EmbassyFX_win_portable.zip'
          if (Test-Path $dst) { Remove-Item -Force $dst }
          Compress-Archive -Path $src -DestinationPath $dst -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmbassyFX_win_portable
          path: packaging/windows/EmbassyFX_win_portable.zip
